version: '3.9'

networks:
  ros:
    driver: bridge

services:
  ros-master:
    image: osrf/ros:noetic-desktop-full
    command: stdbuf -o L roscore
    networks:
      - ros
    restart: always

  rosbridge:
    image: tccoin/docker-ros:rosbridge
    container_name: rosbridge
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
    ports:
      - "9090:9090"
    networks:
      - ros

  webviz:
    image: cruise/webviz
    container_name: webviz
    ports:
      - "7901:8080"
